USE DB211708033;


CREATE TABLE CHECKOUTSYSTEM
(
  CSID CHAR(2) NOT NULL,
  CSystem VARCHAR(125) NOT NULL,
  PRIMARY KEY (CSID)
);

CREATE TABLE LAYOUT
(
  LayoutID CHAR(1) NOT NULL,
  LayoutDesc VARCHAR(125) NOT NULL,
  PRIMARY KEY (LayoutID)
);

CREATE TABLE STORE_ZAGI
(
  storecid VARCHAR(3) NOT NULL,
  StoreSize INT NOT NULL,
  CSID CHAR(2) NOT NULL,
  LayoutID CHAR(1) NOT NULL,
  PRIMARY KEY (storecid),
  FOREIGN KEY (CSID) REFERENCES CHECKOUTSYSTEM(CSID),
  FOREIGN KEY (LayoutID) REFERENCES LAYOUT(LayoutID)
);

INSERT INTO CHECKOUTSYSTEM VALUES ('CR', 'Cashiers');
INSERT INTO CHECKOUTSYSTEM VALUES ('AC', 'Self Service');
INSERT INTO CHECKOUTSYSTEM VALUES ('MX', 'Mixed');

INSERT INTO LAYOUT VALUES ('M', 'Modern');
INSERT INTO LAYOUT VALUES ('T', 'Traditional');

INSERT INTO STORE_ZAGI VALUES ('S1', '51000', 'CR', 'M');
INSERT INTO STORE_ZAGI VALUES ('S2', '35000', 'AC', 'T');
INSERT INTO STORE_ZAGI VALUES ('S3', '55000', 'MX', 'T');

CREATE TABLE EXTERNAL_CUSTOMER
(
  CustomerID CHAR(7) NOT NULL,
  CustomerName VARCHAR(16) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  MaritalStatus VARCHAR(7) NOT NULL,
  EducationLevel VARCHAR(11) NOT NULL,
  CreditScore INT NOT NULL,

  PRIMARY KEY (CustomerID),
);

INSERT INTO EXTERNAL_CUSTOMER VALUES ('1-2-333', 'Tina', 'Female', 'Single', 'College', '700');
INSERT INTO EXTERNAL_CUSTOMER VALUES ('2-3-444', 'Tony', 'Male', 'Single', 'High School', '650');
INSERT INTO EXTERNAL_CUSTOMER VALUES ('3-4-555', 'Pam', 'Female', 'Married', 'College', '623');
